// src/contexts/LanguageContext.tsx
import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'id';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.myOrders': 'My Orders',
    'nav.newOrder': 'New Order',
    'nav.myAccount': 'My Account',

    // Common
    'common.back': 'Back',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.confirm': 'Confirm',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.close': 'Close',
    'common.total': 'Total',

    // Language
    'lang.switch': 'Language',
    'lang.english': 'English',
    'lang.indonesian': 'Bahasa Indonesia',

    // Login
    'login.title': 'Order Water',
    'login.subtitle': 'Enter your WhatsApp number',
    'login.whatsappLabel': 'WhatsApp Number',
    'login.whatsappPlaceholder': '812-3456-7890',
    'login.continue': 'Continue',
    'login.checking': 'Checking...',
    'login.notRegistered': 'Number not registered. Please register.',
    'login.register': 'Register Now',
    'login.noAccount': "Don't have an account?",
    'login.registerHere': 'Register here',
    'login.tryOtherNumber': 'Try another number',
    'login.functionsUnreachable':
      'Cannot reach the server. Check your internet, VPN, or ad blocker. Local dev: run `supabase start` and use VITE_SUPABASE_MODE=local if needed.',
    'login.functions401':
      'Server rejected the API key (401). Edge Functions need the Legacy anon JWT (starts with eyJ) in VITE_SUPABASE_ANON_KEY — not the sb_publishable key. Dashboard → Settings → API → Legacy API keys.',

    // Register
    'register.title': 'Welcome!',
    'register.subtitle': 'Create new account',
    'register.step1': 'Step 1: Fill the form',
    'register.step2': 'Step 2: Verify WhatsApp OTP',
    'register.formTitle': 'Registration Form',
    'register.otpTitle': 'WhatsApp Verification',
    'register.otpSubtitle': 'Enter the OTP code sent to your WhatsApp',
    'register.nameLabel': 'Full Name',
    'register.namePlaceholder': 'John Doe',
    'register.addressLabel': 'Delivery Address',
    'register.addressPlaceholder': 'Jl. Sudirman No. 123, South Jakarta',
    'register.whatsappLabel': 'WhatsApp Number',
    'register.buttonNext': 'Next',
    'register.buttonSending': 'Sending OTP...',
    'register.buttonVerify': 'Complete Registration',
    'register.buttonVerifying': 'Creating Account...',
    'register.otpExpires': 'Code expires in',
    'register.resendOtp': 'Resend OTP code',
    'register.resendIn': 'Resend in',
    'register.changeNumber': 'Change Number',
    'register.haveAccount': 'Already have an account?',
    'register.checkWhatsapp': 'Check your WhatsApp for order link',
    'register.nextStep': 'Next step:',
    'register.openWhatsapp': 'Open your WhatsApp and click the link sent to start ordering!',
    'register.footerBonus': 'Welcome voucher available for eligible new customers',
    'register.errorRequired': 'Please fill all required fields',
    'register.successTitle': 'Registration Successful!',
    'register.successMessage': 'Order link has been sent to your WhatsApp. Please check WhatsApp to continue.',
    'register.registrationComplete': 'Registration Complete',
    'register.alreadyRegistered': "You're already registered!",
    'register.loginLinkSent': 'Login link has been sent to your WhatsApp.',
    'register.openChat': 'Open chat with us',
    'register.enterDashboard': 'Enter Dashboard',
    'register.backToLogin': 'Back to login',
    'register.numberRegistered': 'Number already registered. Please login.',
    'register.didntReceive': "Didn't receive? Click the button below.",
    'register.lostLink': 'Lost your link?',
    'register.getNewLink': 'Get new link',
    'register.creatingAccount': 'Creating your account...',
    'register.newOtpSent': 'New OTP code has been sent!',

    // Home
    'home.signOut': 'Sign Out',
    'home.prepaid': 'Prepaid (Voucher)',
    'home.postpaid': 'Postpaid (Invoice)',
    'home.voucherBalance': 'Voucher Balance',
    'home.noVouchers': 'No vouchers yet',
    'home.pendingOrders': 'Active Orders',
    'home.statusPending': 'Awaiting Dispatch',
    'home.statusScheduled': 'Scheduled',
    'home.details': 'Details',
    'orders.statusDelivered': 'Delivered',
    'orders.statusCancelled': 'Cancelled',
    'home.delivery': 'Delivery:',
    'home.amount': 'Amount:',
    'home.scheduledMsg': 'Order is scheduled — cannot be edited',
    'home.orderDelivery': 'Order Delivery',
    'home.buyVouchers': 'Buy Vouchers',
    'home.quickInfo': 'Quick Info',
    'home.accountStatus': 'Account Status',
    'home.active': 'Active',
    'home.pendingSetup': 'Pending Setup',
    'home.serviceBranch': 'Service Branch',
    'home.billingCycle': 'Billing Cycle',
    'home.onDelivery': 'On Delivery',
    'home.unpaidAmount': 'Unpaid Amount',
    'home.creditUsed': 'Credit Used',
    'home.creditLimit': 'Credit Limit',
    'home.allPaid': 'All paid',
    'home.payNow': 'Pay Now',
    'home.lastDelivery': 'Last Delivery',
    'home.shareApp': 'Share App',
    'home.scanShare': 'Scan or share to open the app',
    'home.share': 'Share',
    'home.copyLink': 'Copy Link',
    'home.linkCopied': 'Link copied!',
    'home.noPendingOrders': 'No active orders',
    'home.loading': 'Loading...',

    // Branch Selection
    'branch.title': 'Choose Your Water Branch',
    'branch.greeting': 'Search your address to find the nearest branch.',
    'branch.searchPlaceholder': 'Search your address...',
    'branch.searchHint': 'Tap and select your address from the dropdown to find nearby branches',
    'branch.yourLocation': 'Your location',
    'branch.allBranches': 'All branches (none in service area)',
    'branch.nearbyBranches': 'Nearby branches',
    'branch.kmAway': 'km away',
    'branch.selected': 'Selected',
    'branch.selectAbove': 'Select a branch above',
    'branch.confirm': 'Confirm',
    'branch.saving': 'Saving...',
    'branch.sessionExpired': 'Session expired. Please log in again.',
    'branch.saveFailed': 'Failed to save. Please try again.',
    'branch.demoForbidden': 'This branch is for internal testing only.',
    'branch.loading': 'Loading...',

    // Vouchers / Top Up
    'vouchers.title': 'Top Up',
    'vouchers.notAvailable': 'Vouchers Not Available',
    'vouchers.postpaidMsg': 'Your account is postpaid mode.\nVouchers are only for prepaid customers.',
    'vouchers.currentBalance': 'Current Balance',
    'vouchers.refillPackages': 'Refill Packages',
    'vouchers.perVoucher': 'Per Voucher',
    'vouchers.perVoucherPrice': '/ voucher',
    'vouchers.otherProducts': 'Other Products',
    'vouchers.noProducts': 'No products available.',
    'vouchers.buyNow': 'Buy Now',
    'vouchers.loading': 'Loading...',
    'vouchers.autoAdd': 'Balance is automatically added after successful payment.',
    'vouchers.paymentSuccess': 'Payment successful! Vouchers added.',
    'vouchers.paymentPending': 'Payment submitted — vouchers will be added once payment settles.',
    'vouchers.paymentFailed': 'Payment failed: ',
    'vouchers.paymentError': 'Payment error: ',
    'vouchers.backToHome': '← Back to Home',
    'vouchers.loadingPayment': 'Loading...',
    'vouchers.historyPurchaseTitle': 'Purchase history',
    'vouchers.historyUsageTitle': 'Voucher usage',
    'vouchers.historyPurchaseEmpty': 'No purchase records yet.',
    'vouchers.historyUsageEmpty': 'No usage yet.',
    'vouchers.historyNote':
      'Shows online (Midtrans) purchases only. Welcome credits or manual adjustments are not listed.',
    'vouchers.statusPending': 'Payment pending',
    'vouchers.statusConfirmed': 'Completed',
    'vouchers.statusRejected': 'Rejected',
    'vouchers.statusInvalid': 'Invalid (expired)',
    'vouchers.expiresOn': 'Expires on:',
    'vouchers.expiredOn': 'Expired on:',
    'vouchers.expiryWarningPrefix': 'Reminder:',
    'vouchers.expiryWarningSuffix': 'voucher purchase(s) will expire within 1 month.',
    'vouchers.usageUsed': 'Used',
    'vouchers.usageReturned': 'Returned',
    'vouchers.usageReturnedHint': 'Order cancelled — vouchers restored.',
    'vouchers.tickets': 'tickets',
    'vouchers.giftVoucher': 'Welcome / gift',
    'vouchers.delivery': 'Delivery',

    // Account
    'account.title': 'My Account',
    'account.profile': 'Profile',
    'account.settings': 'Settings',
    'account.logout': 'Sign Out',
    'account.prepaid': 'Prepaid',
    'account.postpaid': 'Postpaid',
    'account.deliveryAddress': 'Delivery Address',
    'account.whatsapp': 'WhatsApp',
    'account.serviceBranch': 'Service Branch',
    'account.pendingSetup': 'Pending Setup',
    'account.notAssigned': 'Not assigned',
    'account.branchManagedBySales': 'Your service branch is set by your account manager and cannot be changed here.',
    'branch.laterPayCannotChange': 'Postpaid accounts cannot change service branch in the app.',
    'branch.laterPaySetupAnomaly': 'Please contact your sales office to confirm your branch.',
    'account.voucherBalance': 'Voucher Balance',
    'account.noVouchers': 'No vouchers yet',
    'account.orderHistory': 'Order History',
    'account.addressUpdated': 'Address updated!',
    'account.updateFailed': 'Failed to update address: ',
    'account.saving': 'Saving...',
    'account.save': 'Save',
    'account.cancel': 'Cancel',
    'account.edit': 'Edit',

    // Place Order
    'placeOrder.title': 'Place New Order',
    'placeOrder.newDelivery': 'New Delivery',
    'placeOrder.editOrder': 'Edit Order',
    'placeOrder.selectProducts': 'Select Products',
    'placeOrder.deliveryDate': 'Delivery Date',
    'placeOrder.notes': 'Notes (Optional)',
    'placeOrder.notesPlaceholder': 'E.g. Please leave at the door...',
    'placeOrder.orderSummary': 'Order Summary',
    'placeOrder.submit': 'Place Order',
    'placeOrder.update': 'Update Order',
    'placeOrder.submitting': 'Submitting...',
    'placeOrder.processing': 'Processing...',
    'placeOrder.loadingProducts': 'Loading products...',
    'placeOrder.noProducts': 'No products available.',
    'placeOrder.voucherBadge': 'voucher',
    'placeOrder.buy': 'Buy',
    'placeOrder.currentVouchers': 'Current Vouchers',
    'placeOrder.paymentBreakdown': 'Payment Breakdown',
    'placeOrder.voucherCovered': 'covered by vouchers',
    'placeOrder.giftTicket': 'free',
    'placeOrder.payViaQris': 'Pay via QRIS',
    'placeOrder.onCredit': 'On Credit',
    'placeOrder.remaining': 'remaining',
    'placeOrder.coveredBy': 'Voucher covers',
    'placeOrder.atFullPrice': 'At full price',
    'placeOrder.creditLimitExceeded': 'Credit Limit Exceeded',
    'placeOrder.creditLimitDesc': 'This order would exceed your available credit limit',
    'placeOrder.outstandingBalance': 'Outstanding Balance',
    'placeOrder.outstandingDesc': 'You have unpaid delivered orders. Please settle your balance before placing a new order.',
    'placeOrder.prePayRequiresPaymentTitle': 'Payment required',
    'placeOrder.prePayRequiresPaymentDesc':
      'Please pay via QRIS before the order is confirmed. Use the Pay with QRIS button when there is an amount due.',
    'placeOrder.viewPayBills': 'View & Pay Bills',
    'placeOrder.backToHome': 'Back to Home',
    'placeOrder.orderPlaced': 'Order Placed!',
    'placeOrder.orderUpdated': 'Order Updated!',
    'placeOrder.orderPlacedDesc': 'Your order has been received. We will arrange delivery soon.',
    'placeOrder.orderUpdatedDesc': 'Your order has been updated successfully.',
    'placeOrder.unpaidBills': 'Unpaid Bills',
    'placeOrder.unpaidBillsDesc': 'You have unpaid bills. Please settle before placing a new order.',
    'placeOrder.accessories': 'Accessories',
    'placeOrder.showAccessories': 'Show Accessories',
    'placeOrder.hideAccessories': 'Hide Accessories',
    'placeOrder.deliveryScheduleTitle': 'Delivery schedule',
    'placeOrder.deliveryCutoffLine':
      'Daily cutoff is {hour}:00 (WIB). Orders placed after that time are scheduled for the next delivery day.',
    'placeOrder.deliveryRestDaysLine': 'No delivery on: {days} (weekly rest days for your branch).',
    'placeOrder.deliveryRestDaysNone': 'Your branch is set to deliver every day of the week.',
    'placeOrder.dismissNotice': 'Got it',
    'placeOrder.deliveryDateTooSoon': 'Please choose the earliest available delivery date.',
    'placeOrder.deliveryDateBranchClosed': 'That day is closed for delivery. Date moved to the next available day.',
    'placeOrder.deliveryDateTooSoonTitle': 'Delivery date too soon',
    'placeOrder.deliveryDateTooSoonDesc':
      'Orders must be for today (before cutoff) or later. After the daily cutoff, the earliest day is tomorrow.',
    'placeOrder.deliveryDateClosedTitle': 'Rest day',
    'placeOrder.deliveryDateClosedDesc': 'Your branch does not deliver on that weekday. Please pick another date.',
    'placeOrder.disc': 'disc.',
    'placeOrder.failedLoadProducts': 'Failed to load products: ',
    'placeOrder.failedLoadOrder': 'Failed to load order: ',
    'placeOrder.selectProductError': 'Please select at least one product.',
    'placeOrder.selectDateError': 'Please select a delivery date.',
    'placeOrder.paymentPendingToast':
      'Payment submitted — your order will be confirmed once payment settles.',
    'placeOrder.paymentNotCompletedToast':
      'Payment not completed. Your order is saved — you can pay from Order History.',
    'placeOrder.paymentFailedPrefix': 'Payment failed: ',
    'placeOrder.failedSubmit': 'Failed to submit: ',
    'placeOrder.sessionExpired': 'Session expired, please login again',
    'placeOrder.refillBarrelNoticeTitle': 'Refill: empty Vividaqua gallon required',
    'placeOrder.refillBarrelNoticeBody':
      'For each refill delivery, please have a Vividaqua empty 19L gallon ready for exchange. Without an empty Vividaqua gallon, our staff may not be able to complete delivery.',
    'placeOrder.refillBarrelNoticeGiftTitle': 'Using a free voucher for refill?',
    'placeOrder.refillBarrelNoticeGiftBody':
      'Free welcome vouchers cover the refill service only — they do not include a bottle. You must still provide a Vividaqua empty gallon for exchange. Without it, delivery may not be completed.',

    'pwaInstall.title': 'Add VividAqua to your home screen?',
    'pwaInstall.body':
      'Open it faster next time with an icon on your home screen. Use the button below or follow the steps.',
    'pwaInstall.installNow': 'Add to home screen',
    'pwaInstall.later': 'Remind me later',
    'pwaInstall.never': "Don't ask again",
    'pwaInstall.iosStep1': 'Tap the Share button at the bottom of Safari (square with arrow).',
    'pwaInstall.iosStep2': 'Scroll and tap “Add to home screen”, then tap Add.',
    'pwaInstall.androidManual':
      'Open your browser menu (⋮) and choose “Add to home screen” or similar.',

    // Order History
    'orders.title': 'Order History',
    'orders.empty': 'No Orders Yet',
    'orders.emptyDesc': "You haven't placed any orders yet.\nStart ordering to see your history here!",
    'orders.startOrdering': 'Start Ordering',
    'orders.errorLoading': 'Error Loading Orders',
    'orders.tryAgain': 'Try Again',
    'orders.orderId': 'Order',
    'orders.deliveryDate': 'Delivery Date',
    'orders.totalAmount': 'Total Amount',
    'orders.paymentStatus': 'Payment Status',
    'orders.orderedOn': 'Ordered on',
    'orders.viewDetails': 'View Delivery Details',
    'orderHistory.outstandingBalance': 'Outstanding Balance',
    'orderHistory.clear': 'Clear',
    'orderHistory.borrowedGallons': 'Borrowed Gallons',
    'orderHistory.payViaQris': 'Pay via QRIS',
    'orderHistory.bankTransfer': 'Bank Transfer',
    'orderHistory.loading': 'Loading orders...',
    'orderHistory.newOrder': 'New Order',
    'orderHistory.paid': 'Paid',
    'orderHistory.unpaid': 'Unpaid',
    'orderHistory.orderConfirmedLocked': 'Paid — order confirmed and locked',
    'orderHistory.awaitingPayment': 'Awaiting payment',
    'orderHistory.completePaymentQris': 'Complete Payment (QRIS)',
    'orderHistory.orderConfirmed': 'Order confirmed — cannot be edited or cancelled',
    'orderHistory.viewPaymentReceipt': 'View Payment Receipt',
    'orderHistory.bank': 'Bank',
    'orderHistory.accountNumber': 'Account Number',
    'orderHistory.accountName': 'Account Name',
    'orderHistory.transferAmount': 'Transfer amount:',
    'orderHistory.uploadReceipt': 'Upload Payment Receipt',
    'orderHistory.receiptUploaded': 'Receipt uploaded successfully!',
    'orderHistory.confirmSoon': 'We will confirm your payment shortly.',
    'orderHistory.selectPhoto': 'Select Photo',
    'orderHistory.submitReceipt': 'Submit Receipt',
    'orderHistory.uploading': 'Uploading...',
    'orderHistory.paymentReceipt': 'Payment Receipt',
    'orderHistory.cancelConfirm': 'Are you sure you want to cancel this order?',
    'orderHistory.paymentSuccess': 'Payment successful!',
    'orderHistory.paymentPending': 'Payment submitted — order will be confirmed once your bank settles the transfer.',
    'orderHistory.paymentFailed': 'Payment failed:',
    'orderHistory.cancelFailed': 'Cancel failed:',
    'orderHistory.sessionExpired': 'Session expired, please login again',
    'orderHistory.loadFailed': 'Failed to load orders',
    'orderHistory.uploadFailed': 'Upload failed:',
    'orderHistory.evidenceFailed': 'Failed to load evidence:',

    // Order Delivery
    'delivery.title': 'Delivery Details',
    'delivery.orderStatus': 'Order Status',
    'delivery.deliveryInfo': 'Delivery Information',
    'delivery.orderDetails': 'Order Details',
    'delivery.customerName': 'Customer Name',
    'delivery.deliveryAddress': 'Delivery Address',
    'delivery.contactPhone': 'Contact Phone',
    'delivery.deliveryDate': 'Delivery Date',
    'delivery.actualDelivery': 'Actual Delivery',
    'delivery.deliveryNotes': 'Delivery Notes',
    'delivery.confirmReceipt': 'Confirm Receipt',
    'delivery.pleaseConfirm': 'Please confirm that you have received the delivery',
    'delivery.confirmButton': 'Confirm Receipt',
    'delivery.confirming': 'Confirming...',
    'delivery.deliveryComplete': 'Delivery Complete',
    'delivery.thankYou': 'Thank you for your order!',
    'delivery.viewMore': 'View More Orders',
    'delivery.deliveryEvidence': 'Delivery Evidence',
    'delivery.emptyGallons': 'Empty Gallons Returned',
    'delivery.borrowedGallons': 'Borrowed Gallons',
    'delivery.customerDiscount': 'Customer Discount',
    'delivery.orderTotal': 'Order Total',
    'delivery.refill': 'Refill',
    'delivery.tips': 'Please check the goods before confirming',
    'delivery.contact': 'If you have any questions, please contact customer service',
    'delivery.confirmMessage': 'Confirm receipt? This action cannot be undone.',
    'delivery.confirmSuccess': 'Receipt confirmed successfully!',
    'delivery.confirmFailed': 'Confirmation failed',
    'delivery.loadFailed': 'Loading Failed',
    'delivery.orderNotFound': 'Order not found',
    'delivery.returnToList': 'Return to Order List',
    'delivery.loadingOrder': 'Loading order information...',

    // Order Status
    'status.pending': 'Pending',
    'status.scheduled': 'Scheduled',
    'status.delivered': 'Delivered',
    'status.cancelled': 'Cancelled',
    'status.paid': 'Paid',
    'status.unpaid': 'Unpaid',
    'status.confirmed': 'Confirmed',
    'status.outForDelivery': 'Out for Delivery',

    // Progress Steps
    'progress.confirmed': 'Confirmed',
    'progress.delivering': 'Delivering',
    'progress.delivered': 'Delivered',
  },

  id: {
    // Navigation
    'nav.home': 'Beranda',
    'nav.myOrders': 'Pesanan Saya',
    'nav.newOrder': 'Pesan Baru',
    'nav.myAccount': 'Akun Saya',

    // Common
    'common.back': 'Kembali',
    'common.loading': 'Memuat...',
    'common.error': 'Kesalahan',
    'common.success': 'Berhasil',
    'common.confirm': 'Konfirmasi',
    'common.cancel': 'Batal',
    'common.save': 'Simpan',
    'common.close': 'Tutup',
    'common.total': 'Total',

    // Language
    'lang.switch': 'Bahasa',
    'lang.english': 'English',
    'lang.indonesian': 'Bahasa Indonesia',

    // Login
    'login.title': 'Pesan Air',
    'login.subtitle': 'Masukkan nomor WhatsApp Anda',
    'login.whatsappLabel': 'Nomor WhatsApp',
    'login.whatsappPlaceholder': '812-3456-7890',
    'login.continue': 'Lanjut',
    'login.checking': 'Memeriksa...',
    'login.notRegistered': 'Nomor belum terdaftar. Silakan daftar.',
    'login.register': 'Daftar Sekarang',
    'login.noAccount': 'Belum punya akun?',
    'login.registerHere': 'Daftar di sini',
    'login.tryOtherNumber': 'Coba nomor lain',
    'login.functionsUnreachable':
      'Tidak terhubung ke server. Periksa internet, VPN, atau pemblokir iklan. Dev lokal: jalankan `supabase start` dan set VITE_SUPABASE_MODE=local jika perlu.',
    'login.functions401':
      'API key ditolak (401). Edge Functions membutuhkan Legacy anon JWT (awalan eyJ) di VITE_SUPABASE_ANON_KEY — bukan kunci sb_publishable. Dashboard → Settings → API → Legacy API keys.',

    // Register
    'register.title': 'Selamat Datang!',
    'register.subtitle': 'Daftar akun baru',
    'register.step1': 'Langkah 1: Isi formulir',
    'register.step2': 'Langkah 2: Verifikasi OTP WhatsApp',
    'register.formTitle': 'Formulir Pendaftaran',
    'register.otpTitle': 'Verifikasi WhatsApp',
    'register.otpSubtitle': 'Masukkan kode OTP yang dikirim ke WhatsApp Anda',
    'register.nameLabel': 'Nama Lengkap',
    'register.namePlaceholder': 'Budi Santoso',
    'register.addressLabel': 'Alamat Pengiriman',
    'register.addressPlaceholder': 'Jl. Sudirman No. 123, Jakarta Selatan',
    'register.whatsappLabel': 'Nomor WhatsApp',
    'register.buttonNext': 'Lanjut',
    'register.buttonSending': 'Mengirim OTP...',
    'register.buttonVerify': 'Selesaikan Pendaftaran',
    'register.buttonVerifying': 'Membuat Akun...',
    'register.otpExpires': 'Kode berlaku',
    'register.resendOtp': 'Kirim ulang kode OTP',
    'register.resendIn': 'Kirim ulang dalam',
    'register.changeNumber': 'Ubah Nomor',
    'register.haveAccount': 'Sudah punya akun?',
    'register.checkWhatsapp': 'Cek WhatsApp Anda untuk link pesanan',
    'register.nextStep': 'Langkah selanjutnya:',
    'register.openWhatsapp': 'Buka WhatsApp Anda dan klik link yang dikirim untuk mulai memesan!',
    'register.footerBonus': 'Voucher sambutan tersedia untuk pelanggan baru yang memenuhi syarat',
    'register.errorRequired': 'Mohon isi semua field yang diperlukan',
    'register.successTitle': 'Pendaftaran Berhasil!',
    'register.successMessage': 'Link pesanan telah dikirim ke WhatsApp Anda. Silakan cek WhatsApp untuk melanjutkan.',
    'register.registrationComplete': 'Pendaftaran Selesai',
    'register.alreadyRegistered': 'Anda sudah terdaftar!',
    'register.loginLinkSent': 'Link masuk telah dikirim ke WhatsApp Anda.',
    'register.openChat': 'Buka chat dengan kami',
    'register.enterDashboard': 'Masuk ke Dashboard',
    'register.backToLogin': 'Kembali ke login',
    'register.numberRegistered': 'Nomor sudah terdaftar. Silakan login.',
    'register.didntReceive': 'Tidak menerima? Klik tombol di bawah.',
    'register.lostLink': 'Hilang link?',
    'register.getNewLink': 'Dapatkan link baru',
    'register.creatingAccount': 'Membuat akun Anda...',
    'register.newOtpSent': 'Kode OTP baru telah dikirim!',

    // Home
    'home.signOut': 'Keluar',
    'home.prepaid': 'Prabayar (Voucher)',
    'home.postpaid': 'Pascabayar (Invoice)',
    'home.voucherBalance': 'Saldo Voucher',
    'home.noVouchers': 'Belum ada voucher',
    'home.pendingOrders': 'Pesanan Aktif',
    'home.statusPending': 'Menunggu Pengiriman',
    'home.statusScheduled': 'Terjadwal',
    'home.details': 'Detail',
    'orders.statusDelivered': 'Terkirim',
    'orders.statusCancelled': 'Dibatalkan',
    'home.delivery': 'Pengiriman:',
    'home.amount': 'Jumlah:',
    'home.scheduledMsg': 'Pesanan dijadwalkan — tidak dapat diedit',
    'home.orderDelivery': 'Pesan Pengiriman',
    'home.buyVouchers': 'Beli Voucher',
    'home.quickInfo': 'Info Cepat',
    'home.accountStatus': 'Status Akun',
    'home.active': 'Aktif',
    'home.pendingSetup': 'Menunggu Setup',
    'home.serviceBranch': 'Cabang Layanan',
    'home.billingCycle': 'Siklus Tagihan',
    'home.onDelivery': 'Sedang Dikirim',
    'home.unpaidAmount': 'Jumlah Belum Dibayar',
    'home.creditUsed': 'Kredit Terpakai',
    'home.creditLimit': 'Batas Kredit',
    'home.allPaid': 'Semua terbayar',
    'home.payNow': 'Bayar Sekarang',
    'home.lastDelivery': 'Pengiriman Terakhir',
    'home.shareApp': 'Bagikan Aplikasi',
    'home.scanShare': 'Pindai atau bagikan untuk membuka aplikasi',
    'home.share': 'Bagikan',
    'home.copyLink': 'Salin Tautan',
    'home.linkCopied': 'Tautan disalin!',
    'home.noPendingOrders': 'Tidak ada pesanan aktif',
    'home.loading': 'Memuat...',

    // Branch Selection
    'branch.title': 'Pilih Cabang Air Anda',
    'branch.greeting': 'Cari alamat Anda untuk menemukan cabang terdekat.',
    'branch.searchPlaceholder': 'Cari alamat Anda...',
    'branch.searchHint': 'Ketuk dan pilih alamat Anda dari dropdown untuk menemukan cabang terdekat',
    'branch.yourLocation': 'Lokasi Anda',
    'branch.allBranches': 'Semua cabang (tidak ada di area layanan)',
    'branch.nearbyBranches': 'Cabang Terdekat',
    'branch.kmAway': 'km jauhnya',
    'branch.selected': 'Dipilih',
    'branch.selectAbove': 'Pilih cabang di atas',
    'branch.confirm': 'Konfirmasi',
    'branch.saving': 'Menyimpan...',
    'branch.sessionExpired': 'Sesi berakhir. Silakan login kembali.',
    'branch.saveFailed': 'Gagal menyimpan. Silakan coba lagi.',
    'branch.demoForbidden': 'Cabang ini hanya untuk pengujian internal.',
    'branch.loading': 'Memuat...',

    // Vouchers / Top Up
    'vouchers.title': 'Isi Voucher',
    'vouchers.notAvailable': 'Voucher Tidak Tersedia',
    'vouchers.postpaidMsg': 'Akun Anda adalah mode pascabayar.\nVoucher hanya untuk pelanggan prabayar.',
    'vouchers.currentBalance': 'Saldo Saat Ini',
    'vouchers.refillPackages': 'Paket Isi Ulang',
    'vouchers.perVoucher': 'Per Voucher',
    'vouchers.perVoucherPrice': '/ voucher',
    'vouchers.otherProducts': 'Produk Lain',
    'vouchers.noProducts': 'Tidak ada produk tersedia.',
    'vouchers.buyNow': 'Beli Sekarang',
    'vouchers.loading': 'Memuat...',
    'vouchers.autoAdd': 'Saldo otomatis ditambahkan setelah pembayaran berhasil.',
    'vouchers.paymentSuccess': 'Pembayaran berhasil! Voucher ditambahkan.',
    'vouchers.paymentPending': 'Pembayaran dikirim — voucher akan ditambahkan setelah pembayaran selesai.',
    'vouchers.paymentFailed': 'Pembayaran gagal: ',
    'vouchers.paymentError': 'Error pembayaran: ',
    'vouchers.backToHome': '← Kembali ke Beranda',
    'vouchers.loadingPayment': 'Memuat...',
    'vouchers.historyPurchaseTitle': 'Riwayat pembelian',
    'vouchers.historyUsageTitle': 'Penggunaan voucher',
    'vouchers.historyPurchaseEmpty': 'Belum ada riwayat pembelian.',
    'vouchers.historyUsageEmpty': 'Belum ada penggunaan.',
    'vouchers.historyNote':
      'Hanya menampilkan pembelian online (Midtrans). Kredit sambutan atau penyesuaian manual tidak tercantum.',
    'vouchers.statusPending': 'Menunggu pembayaran',
    'vouchers.statusConfirmed': 'Selesai',
    'vouchers.statusRejected': 'Ditolak',
    'vouchers.statusInvalid': 'Invalid (kedaluwarsa)',
    'vouchers.expiresOn': 'Berlaku sampai:',
    'vouchers.expiredOn': 'Kedaluwarsa pada:',
    'vouchers.expiryWarningPrefix': 'Pengingat:',
    'vouchers.expiryWarningSuffix': 'pembelian voucher akan kedaluwarsa dalam waktu kurang dari 1 bulan.',
    'vouchers.usageUsed': 'Terpakai',
    'vouchers.usageReturned': 'Dikembalikan',
    'vouchers.usageReturnedHint': 'Pesanan dibatalkan — voucher dikembalikan.',
    'vouchers.tickets': 'lembar',
    'vouchers.giftVoucher': 'Sambutan / hadiah',
    'vouchers.delivery': 'Pengiriman',

    // Account
    'account.title': 'Akun Saya',
    'account.profile': 'Profil',
    'account.settings': 'Pengaturan',
    'account.logout': 'Keluar',
    'account.prepaid': 'Prabayar',
    'account.postpaid': 'Pascabayar',
    'account.deliveryAddress': 'Alamat Pengiriman',
    'account.whatsapp': 'WhatsApp',
    'account.serviceBranch': 'Cabang Layanan',
    'account.pendingSetup': 'Menunggu Setup',
    'account.notAssigned': 'Belum ditetapkan',
    'account.branchManagedBySales': 'Cabang layanan ditetapkan oleh akun penjualan Anda dan tidak dapat diubah di sini.',
    'branch.laterPayCannotChange': 'Akun pascabayar tidak dapat mengubah cabang layanan di aplikasi.',
    'branch.laterPaySetupAnomaly': 'Silakan hubungi kantor penjualan untuk konfirmasi cabang Anda.',
    'account.voucherBalance': 'Saldo Voucher',
    'account.noVouchers': 'Belum ada voucher',
    'account.orderHistory': 'Riwayat Pesanan',
    'account.addressUpdated': 'Alamat diperbarui!',
    'account.updateFailed': 'Gagal memperbarui alamat: ',
    'account.saving': 'Menyimpan...',
    'account.save': 'Simpan',
    'account.cancel': 'Batal',
    'account.edit': 'Edit',

    // Place Order
    'placeOrder.title': 'Buat Pesanan Baru',
    'placeOrder.newDelivery': 'Pesan Baru',
    'placeOrder.editOrder': 'Edit Pesanan',
    'placeOrder.selectProducts': 'Pilih Produk',
    'placeOrder.deliveryDate': 'Tanggal Pengiriman',
    'placeOrder.notes': 'Catatan (Opsional)',
    'placeOrder.notesPlaceholder': 'Contoh: Taruh di depan pintu...',
    'placeOrder.orderSummary': 'Ringkasan Pesanan',
    'placeOrder.submit': 'Buat Pesanan',
    'placeOrder.update': 'Perbarui Pesanan',
    'placeOrder.submitting': 'Memproses...',
    'placeOrder.processing': 'Memproses...',
    'placeOrder.loadingProducts': 'Memuat produk...',
    'placeOrder.noProducts': 'Tidak ada produk tersedia.',
    'placeOrder.voucherBadge': 'voucher',
    'placeOrder.buy': 'Beli',
    'placeOrder.currentVouchers': 'Voucher Saat Ini',
    'placeOrder.paymentBreakdown': 'Rincian Pembayaran',
    'placeOrder.voucherCovered': 'ditanggung voucher',
    'placeOrder.giftTicket': 'gratis',
    'placeOrder.payViaQris': 'Bayar via QRIS',
    'placeOrder.onCredit': 'Kredit',
    'placeOrder.remaining': 'tersisa',
    'placeOrder.coveredBy': 'Voucher menanggung',
    'placeOrder.atFullPrice': 'Harga penuh',
    'placeOrder.creditLimitExceeded': 'Batas Kredit Terlampaui',
    'placeOrder.creditLimitDesc': 'Pesanan ini akan melebihi batas kredit yang tersedia',
    'placeOrder.outstandingBalance': 'Saldo Tertunggak',
    'placeOrder.outstandingDesc': 'Anda memiliki pesanan terkirim yang belum dibayar. Selesaikan pembayaran sebelum memesan baru.',
    'placeOrder.prePayRequiresPaymentTitle': 'Pembayaran diperlukan',
    'placeOrder.prePayRequiresPaymentDesc':
      'Silakan bayar dengan QRIS sebelum pesanan dikonfirmasi. Gunakan tombol Bayar via QRIS jika ada nominal yang harus dibayar.',
    'placeOrder.viewPayBills': 'Lihat & Bayar Tagihan',
    'placeOrder.backToHome': 'Kembali ke Beranda',
    'placeOrder.orderPlaced': 'Pesanan Dibuat!',
    'placeOrder.orderUpdated': 'Pesanan Diperbarui!',
    'placeOrder.orderPlacedDesc': 'Pesanan Anda telah diterima. Kami akan mengatur pengiriman segera.',
    'placeOrder.orderUpdatedDesc': 'Pesanan Anda berhasil diperbarui.',
    'placeOrder.unpaidBills': 'Tagihan Belum Dibayar',
    'placeOrder.unpaidBillsDesc': 'Anda memiliki tagihan belum dibayar. Selesaikan sebelum memesan baru.',
    'placeOrder.accessories': 'Aksesori',
    'placeOrder.showAccessories': 'Tampilkan Aksesori',
    'placeOrder.hideAccessories': 'Sembunyikan Aksesori',
    'placeOrder.deliveryScheduleTitle': 'Jadwal pengiriman',
    'placeOrder.deliveryCutoffLine':
      'Batas pesanan harian pukul {hour}:00 WIB. Pesanan setelah itu dijadwalkan untuk hari pengiriman berikutnya.',
    'placeOrder.deliveryRestDaysLine': 'Tidak kirim pada: {days} (hari libur mingguan cabang Anda).',
    'placeOrder.deliveryRestDaysNone': 'Cabang Anda diatur kirim setiap hari.',
    'placeOrder.dismissNotice': 'Mengerti',
    'placeOrder.deliveryDateTooSoon': 'Pilih tanggal pengiriman terawal yang tersedia.',
    'placeOrder.deliveryDateBranchClosed': 'Hari itu libur kirim. Tanggal dipindah ke hari berikutnya yang tersedia.',
    'placeOrder.deliveryDateTooSoonTitle': 'Tanggal terlalu awal',
    'placeOrder.deliveryDateTooSoonDesc':
      'Pesanan harus untuk hari ini (sebelum batas waktu) atau setelahnya. Setelah batas harian, hari terawal adalah besok.',
    'placeOrder.deliveryDateClosedTitle': 'Hari libur kirim',
    'placeOrder.deliveryDateClosedDesc': 'Cabang Anda tidak kirim di hari itu. Silakan pilih tanggal lain.',
    'placeOrder.disc': 'disk.',
    'placeOrder.failedLoadProducts': 'Gagal memuat produk: ',
    'placeOrder.failedLoadOrder': 'Gagal memuat pesanan: ',
    'placeOrder.selectProductError': 'Pilih minimal satu produk.',
    'placeOrder.selectDateError': 'Pilih tanggal pengiriman.',
    'placeOrder.paymentPendingToast':
      'Pembayaran dikirim — pesanan akan dikonfirmasi setelah pembayaran selesai.',
    'placeOrder.paymentNotCompletedToast':
      'Pembayaran belum selesai. Pesanan tersimpan — Anda bisa bayar dari Riwayat Pesanan.',
    'placeOrder.paymentFailedPrefix': 'Pembayaran gagal: ',
    'placeOrder.failedSubmit': 'Gagal mengirim: ',
    'placeOrder.sessionExpired': 'Sesi berakhir, silakan login kembali',
    'placeOrder.refillBarrelNoticeTitle': 'Isi ulang: wajib ada galon Vividaqua kosong',
    'placeOrder.refillBarrelNoticeBody':
      'Untuk setiap pengiriman isi ulang, sediakan galon kosong Vividaqua 19L untuk ditukar. Tanpa galon kosong Vividaqua, tim kami mungkin tidak dapat menyelesaikan pengiriman.',
    'placeOrder.refillBarrelNoticeGiftTitle': 'Memakai voucher gratis untuk isi ulang?',
    'placeOrder.refillBarrelNoticeGiftBody':
      'Voucher selamat datang gratis hanya menanggung layanan isi ulang — tidak termasuk botol/galon. Anda tetap harus menyediakan galon kosong Vividaqua untuk ditukar. Tanpa itu, pengiriman mungkin tidak dapat dilakukan.',

    'pwaInstall.title': 'Tambahkan VividAqua ke layar utama?',
    'pwaInstall.body':
      'Buka lebih cepat lain kali lewat ikon di layar utama. Gunakan tombol di bawah atau ikuti langkah-langkahnya.',
    'pwaInstall.installNow': 'Tambah ke layar utama',
    'pwaInstall.later': 'Ingatkan nanti',
    'pwaInstall.never': 'Jangan tanya lagi',
    'pwaInstall.iosStep1': 'Ketuk tombol Bagikan di bawah Safari (kotak dengan panah).',
    'pwaInstall.iosStep2':
      'Gulir dan ketuk “Tambahkan ke Layar Utama”, lalu ketuk Tambah. (Jika menu bahasa Inggris: “Add to Home Screen”.)',
    'pwaInstall.androidManual':
      'Buka menu browser (⋮) dan pilih “Tambahkan ke layar utama” atau opsi serupa.',

    // Order History
    'orders.title': 'Riwayat Pesanan',
    'orders.empty': 'Belum Ada Pesanan',
    'orders.emptyDesc': 'Anda belum melakukan pesanan.\nMulai pesan untuk melihat riwayat di sini!',
    'orders.startOrdering': 'Mulai Pesan',
    'orders.errorLoading': 'Gagal Memuat Pesanan',
    'orders.tryAgain': 'Coba Lagi',
    'orders.orderId': 'Pesanan',
    'orders.deliveryDate': 'Tanggal Pengiriman',
    'orders.totalAmount': 'Total Pembayaran',
    'orders.paymentStatus': 'Status Pembayaran',
    'orders.orderedOn': 'Dipesan pada',
    'orders.viewDetails': 'Lihat Detail Pengiriman',
    'orderHistory.outstandingBalance': 'Saldo Tertunggak',
    'orderHistory.clear': 'Lunas',
    'orderHistory.borrowedGallons': 'Galon Dipinjam',
    'orderHistory.payViaQris': 'Bayar via QRIS',
    'orderHistory.bankTransfer': 'Transfer Bank',
    'orderHistory.loading': 'Memuat pesanan...',
    'orderHistory.newOrder': 'Pesanan Baru',
    'orderHistory.paid': 'Terbayar',
    'orderHistory.unpaid': 'Belum Dibayar',
    'orderHistory.orderConfirmedLocked': 'Terbayar — pesanan dikonfirmasi dan terkunci',
    'orderHistory.awaitingPayment': 'Menunggu pembayaran',
    'orderHistory.completePaymentQris': 'Selesaikan Pembayaran (QRIS)',
    'orderHistory.orderConfirmed': 'Pesanan dikonfirmasi — tidak dapat diedit atau dibatalkan',
    'orderHistory.viewPaymentReceipt': 'Lihat Kuitansi Pembayaran',
    'orderHistory.bank': 'Bank',
    'orderHistory.accountNumber': 'Nomor Rekening',
    'orderHistory.accountName': 'Nama Rekening',
    'orderHistory.transferAmount': 'Jumlah transfer:',
    'orderHistory.uploadReceipt': 'Unggah Kuitansi Pembayaran',
    'orderHistory.receiptUploaded': 'Kuitansi berhasil diunggah!',
    'orderHistory.confirmSoon': 'Kami akan mengkonfirmasi pembayaran Anda segera.',
    'orderHistory.selectPhoto': 'Pilih Foto',
    'orderHistory.submitReceipt': 'Kirim Kuitansi',
    'orderHistory.uploading': 'Mengunggah...',
    'orderHistory.paymentReceipt': 'Kuitansi Pembayaran',
    'orderHistory.cancelConfirm': 'Anda yakin ingin membatalkan pesanan ini?',
    'orderHistory.paymentSuccess': 'Pembayaran berhasil!',
    'orderHistory.paymentPending': 'Pembayaran dikirim — pesanan akan dikonfirmasi setelah bank menyelesaikan transfer.',
    'orderHistory.paymentFailed': 'Pembayaran gagal:',
    'orderHistory.cancelFailed': 'Pembatalan gagal:',
    'orderHistory.sessionExpired': 'Sesi berakhir, silakan login kembali',
    'orderHistory.loadFailed': 'Gagal memuat pesanan',
    'orderHistory.uploadFailed': 'Unggah gagal:',
    'orderHistory.evidenceFailed': 'Gagal memuat bukti:',

    // Order Delivery
    'delivery.title': 'Detail Pengiriman',
    'delivery.orderStatus': 'Status Pesanan',
    'delivery.deliveryInfo': 'Informasi Pengiriman',
    'delivery.orderDetails': 'Detail Pesanan',
    'delivery.customerName': 'Nama Pelanggan',
    'delivery.deliveryAddress': 'Alamat Pengiriman',
    'delivery.contactPhone': 'Nomor Telepon',
    'delivery.deliveryDate': 'Tanggal Pengiriman',
    'delivery.actualDelivery': 'Pengiriman Aktual',
    'delivery.deliveryNotes': 'Catatan Pengiriman',
    'delivery.confirmReceipt': 'Konfirmasi Penerimaan',
    'delivery.pleaseConfirm': 'Mohon konfirmasi bahwa Anda telah menerima pengiriman',
    'delivery.confirmButton': 'Konfirmasi Penerimaan',
    'delivery.confirming': 'Mengonfirmasi...',
    'delivery.deliveryComplete': 'Pengiriman Selesai',
    'delivery.thankYou': 'Terima kasih atas pesanan Anda!',
    'delivery.viewMore': 'Lihat Pesanan Lainnya',
    'delivery.deliveryEvidence': 'Bukti Pengiriman',
    'delivery.emptyGallons': 'Galon Kosong Dikembalikan',
    'delivery.borrowedGallons': 'Galon Dipinjam',
    'delivery.customerDiscount': 'Diskon Pelanggan',
    'delivery.orderTotal': 'Total Pesanan',
    'delivery.refill': 'Isi Ulang',
    'delivery.tips': 'Silakan periksa barang sebelum mengonfirmasi',
    'delivery.contact': 'Jika ada pertanyaan, hubungi layanan pelanggan',
    'delivery.confirmMessage': 'Konfirmasi penerimaan? Tindakan ini tidak dapat dibatalkan.',
    'delivery.confirmSuccess': 'Penerimaan berhasil dikonfirmasi!',
    'delivery.confirmFailed': 'Konfirmasi gagal',
    'delivery.loadFailed': 'Gagal Memuat',
    'delivery.orderNotFound': 'Pesanan tidak ditemukan',
    'delivery.returnToList': 'Kembali ke Daftar Pesanan',
    'delivery.loadingOrder': 'Memuat informasi pesanan...',

    // Order Status
    'status.pending': 'Menunggu',
    'status.scheduled': 'Dijadwalkan',
    'status.delivered': 'Terkirim',
    'status.cancelled': 'Dibatalkan',
    'status.paid': 'Dibayar',
    'status.unpaid': 'Belum Dibayar',
    'status.confirmed': 'Dikonfirmasi',
    'status.outForDelivery': 'Dalam Pengiriman',

    // Progress Steps
    'progress.confirmed': 'Dikonfirmasi',
    'progress.delivering': 'Dalam Pengiriman',
    'progress.delivered': 'Terkirim',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app_language');
    return (saved === 'en' || saved === 'id') ? saved : 'id';
  });

  useEffect(() => {
    localStorage.setItem('app_language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
