// src/contexts/LanguageContext.tsx
import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'id';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.myOrders': 'My Orders',
    'nav.newOrder': 'New Order',
    'nav.myAccount': 'My Account',

    // Common
    'common.back': 'Back',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.confirm': 'Confirm',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.close': 'Close',
    'common.total': 'Total',

    // Language
    'lang.switch': 'Language',
    'lang.english': 'English',
    'lang.indonesian': 'Bahasa Indonesia',

    // Login
    'login.title': 'Order Water',
    'login.subtitle': 'Enter your WhatsApp number',
    'login.whatsappLabel': 'WhatsApp Number',
    'login.whatsappPlaceholder': '812-3456-7890',
    'login.continue': 'Continue',
    'login.checking': 'Checking...',
    'login.notRegistered': 'Number not registered. Please register.',
    'login.register': 'Register Now',
    'login.noAccount': "Don't have an account?",
    'login.registerHere': 'Register here',
    'login.tryOtherNumber': 'Try another number',

    // Register
    'register.title': 'Welcome!',
    'register.subtitle': 'Create new account',
    'register.step1': 'Step 1: Fill the form',
    'register.step2': 'Step 2: Verify WhatsApp OTP',
    'register.formTitle': 'Registration Form',
    'register.otpTitle': 'WhatsApp Verification',
    'register.otpSubtitle': 'Enter the OTP code sent to your WhatsApp',
    'register.nameLabel': 'Full Name',
    'register.namePlaceholder': 'John Doe',
    'register.addressLabel': 'Delivery Address',
    'register.addressPlaceholder': 'Jl. Sudirman No. 123, South Jakarta',
    'register.whatsappLabel': 'WhatsApp Number',
    'register.buttonNext': 'Next',
    'register.buttonSending': 'Sending OTP...',
    'register.buttonVerify': 'Complete Registration',
    'register.buttonVerifying': 'Creating Account...',
    'register.otpExpires': 'Code expires in',
    'register.resendOtp': 'Resend OTP code',
    'register.resendIn': 'Resend in',
    'register.changeNumber': 'Change Number',
    'register.haveAccount': 'Already have an account?',
    'register.checkWhatsapp': 'Check your WhatsApp for order link',
    'register.nextStep': 'Next step:',
    'register.openWhatsapp': 'Open your WhatsApp and click the link sent to start ordering!',
    'register.footerBonus': 'Get 2 free vouchers upon registration',
    'register.errorRequired': 'Please fill all required fields',
    'register.successTitle': 'Registration Successful!',
    'register.successMessage': 'Order link has been sent to your WhatsApp. Please check WhatsApp to continue.',
    'register.registrationComplete': 'Registration Complete',
    'register.alreadyRegistered': "You're already registered!",
    'register.loginLinkSent': 'Login link has been sent to your WhatsApp.',
    'register.openChat': 'Open chat with us',
    'register.enterDashboard': 'Enter Dashboard',
    'register.backToLogin': 'Back to login',
    'register.numberRegistered': 'Number already registered. Please login.',
    'register.didntReceive': "Didn't receive? Click the button below.",
    'register.lostLink': 'Lost your link?',
    'register.getNewLink': 'Get new link',
    'register.creatingAccount': 'Creating your account...',
    'register.newOtpSent': 'New OTP code has been sent!',

    // Home
    'home.signOut': 'Sign Out',
    'home.prepaid': 'Prepaid (Voucher)',
    'home.postpaid': 'Postpaid (Invoice)',
    'home.voucherBalance': 'Voucher Balance',
    'home.noVouchers': 'No vouchers yet',
    'home.pendingOrders': 'Pending Orders',
    'home.delivery': 'Delivery:',
    'home.amount': 'Amount:',
    'home.scheduledMsg': 'Order is scheduled — cannot be edited',
    'home.orderDelivery': 'Order Delivery',
    'home.buyVouchers': 'Buy Vouchers',
    'home.quickInfo': 'Quick Info',
    'home.accountStatus': 'Account Status',
    'home.active': 'Active',
    'home.pendingSetup': 'Pending Setup',
    'home.serviceBranch': 'Service Branch',
    'home.billingCycle': 'Billing Cycle',
    'home.onDelivery': 'On Delivery',
    'home.unpaidAmount': 'Unpaid Amount',
    'home.allPaid': 'All paid',
    'home.payNow': 'Pay Now',
    'home.lastDelivery': 'Last Delivery',
    'home.shareApp': 'Share App',
    'home.scanShare': 'Scan or share to open the app',
    'home.share': 'Share',
    'home.copyLink': 'Copy Link',
    'home.linkCopied': 'Link copied!',
    'home.deleteConfirm': 'Are you sure you want to delete this order?',
    'home.deleteSuccess': 'Order deleted!',
    'home.deleteFailed': 'Delete failed: ',
    'home.noPendingOrders': 'No pending orders',
    'home.loading': 'Loading...',
    'home.edit': 'Edit',
    'home.delete': 'Delete',

    // Branch Selection
    'branch.title': 'Choose Your Water Branch',
    'branch.greeting': 'Search your address to find the nearest branch.',
    'branch.searchPlaceholder': 'Search your address...',
    'branch.searchHint': 'Tap and select your address from the dropdown to find nearby branches',
    'branch.yourLocation': 'Your location',
    'branch.allBranches': 'All branches (none in service area)',
    'branch.nearbyBranches': 'Nearby branches',
    'branch.kmAway': 'km away',
    'branch.selected': 'Selected',
    'branch.selectAbove': 'Select a branch above',
    'branch.confirm': 'Confirm',
    'branch.saving': 'Saving...',
    'branch.sessionExpired': 'Session expired. Please log in again.',
    'branch.saveFailed': 'Failed to save. Please try again.',
    'branch.loading': 'Loading...',

    // Vouchers / Top Up
    'vouchers.title': 'Top Up',
    'vouchers.notAvailable': 'Vouchers Not Available',
    'vouchers.postpaidMsg': 'Your account is postpaid mode.\nVouchers are only for prepaid customers.',
    'vouchers.currentBalance': 'Current Balance',
    'vouchers.refillPackages': 'Refill Packages',
    'vouchers.perVoucher': 'Per Voucher',
    'vouchers.perVoucherPrice': '/ voucher',
    'vouchers.otherProducts': 'Other Products',
    'vouchers.noProducts': 'No products available.',
    'vouchers.buyNow': 'Buy Now',
    'vouchers.loading': 'Loading...',
    'vouchers.autoAdd': 'Balance is automatically added after successful payment.',
    'vouchers.paymentSuccess': 'Payment successful! Vouchers added.',
    'vouchers.paymentPending': 'Payment submitted — vouchers will be added once payment settles.',
    'vouchers.paymentFailed': 'Payment failed: ',
    'vouchers.paymentError': 'Payment error: ',
    'vouchers.backToHome': '← Back to Home',
    'vouchers.loadingPayment': 'Loading...',

    // Account
    'account.title': 'My Account',
    'account.profile': 'Profile',
    'account.settings': 'Settings',
    'account.logout': 'Sign Out',
    'account.prepaid': 'Prepaid',
    'account.postpaid': 'Postpaid',
    'account.deliveryAddress': 'Delivery Address',
    'account.whatsapp': 'WhatsApp',
    'account.serviceBranch': 'Service Branch',
    'account.pendingSetup': 'Pending Setup',
    'account.notAssigned': 'Not assigned',
    'account.voucherBalance': 'Voucher Balance',
    'account.noVouchers': 'No vouchers yet',
    'account.orderHistory': 'Order History',
    'account.addressUpdated': 'Address updated!',
    'account.updateFailed': 'Failed to update address: ',
    'account.saving': 'Saving...',
    'account.save': 'Save',
    'account.cancel': 'Cancel',
    'account.edit': 'Edit',

    // Place Order
    'placeOrder.title': 'Place New Order',
    'placeOrder.newDelivery': 'New Delivery',
    'placeOrder.editOrder': 'Edit Order',
    'placeOrder.selectProducts': 'Select Products',
    'placeOrder.deliveryDate': 'Delivery Date',
    'placeOrder.notes': 'Notes (Optional)',
    'placeOrder.notesPlaceholder': 'E.g. Please leave at the door...',
    'placeOrder.orderSummary': 'Order Summary',
    'placeOrder.submit': 'Place Order',
    'placeOrder.update': 'Update Order',
    'placeOrder.submitting': 'Submitting...',
    'placeOrder.processing': 'Processing...',
    'placeOrder.loadingProducts': 'Loading products...',
    'placeOrder.noProducts': 'No products available.',
    'placeOrder.voucherBadge': 'voucher',
    'placeOrder.buy': 'Buy',
    'placeOrder.paymentBreakdown': 'Payment Breakdown',
    'placeOrder.voucherCovered': 'covered by vouchers',
    'placeOrder.payViaQris': 'Pay via QRIS',
    'placeOrder.outstandingBalance': 'Outstanding Balance',
    'placeOrder.outstandingDesc': 'You have unpaid delivered orders. Please settle your balance before placing a new order.',
    'placeOrder.viewPayBills': 'View & Pay Bills',
    'placeOrder.backToHome': 'Back to Home',
    'placeOrder.orderPlaced': 'Order Placed!',
    'placeOrder.orderUpdated': 'Order Updated!',
    'placeOrder.orderPlacedDesc': 'Your order has been received. We will arrange delivery soon.',
    'placeOrder.orderUpdatedDesc': 'Your order has been updated successfully.',
    'placeOrder.unpaidBills': 'Unpaid Bills',
    'placeOrder.unpaidBillsDesc': 'You have unpaid bills. Please settle before placing a new order.',
    'placeOrder.accessories': 'Accessories',
    'placeOrder.showAccessories': 'Show Accessories',
    'placeOrder.hideAccessories': 'Hide Accessories',
    'placeOrder.disc': 'disc.',
    'placeOrder.failedSubmit': 'Failed to submit: ',
    'placeOrder.sessionExpired': 'Session expired, please login again',

    // Order History
    'orders.title': 'Order History',
    'orders.empty': 'No Orders Yet',
    'orders.emptyDesc': "You haven't placed any orders yet.\nStart ordering to see your history here!",
    'orders.startOrdering': 'Start Ordering',
    'orders.errorLoading': 'Error Loading Orders',
    'orders.tryAgain': 'Try Again',
    'orders.orderId': 'Order',
    'orders.deliveryDate': 'Delivery Date',
    'orders.totalAmount': 'Total Amount',
    'orders.paymentStatus': 'Payment Status',
    'orders.orderedOn': 'Ordered on',
    'orders.viewDetails': 'View Delivery Details',
    'orderHistory.outstandingBalance': 'Outstanding Balance',
    'orderHistory.clear': 'Clear',
    'orderHistory.borrowedGallons': 'Borrowed Gallons',
    'orderHistory.payViaQris': 'Pay via QRIS',
    'orderHistory.bankTransfer': 'Bank Transfer',
    'orderHistory.loading': 'Loading orders...',
    'orderHistory.newOrder': 'New Order',
    'orderHistory.paid': 'Paid',
    'orderHistory.unpaid': 'Unpaid',
    'orderHistory.orderConfirmedLocked': 'Paid — order confirmed and locked',
    'orderHistory.awaitingPayment': 'Awaiting payment',
    'orderHistory.completePaymentQris': 'Complete Payment (QRIS)',
    'orderHistory.orderConfirmed': 'Order confirmed — cannot be edited or cancelled',
    'orderHistory.viewPaymentReceipt': 'View Payment Receipt',
    'orderHistory.bank': 'Bank',
    'orderHistory.accountNumber': 'Account Number',
    'orderHistory.accountName': 'Account Name',
    'orderHistory.transferAmount': 'Transfer amount:',
    'orderHistory.uploadReceipt': 'Upload Payment Receipt',
    'orderHistory.receiptUploaded': 'Receipt uploaded successfully!',
    'orderHistory.confirmSoon': 'We will confirm your payment shortly.',
    'orderHistory.selectPhoto': 'Select Photo',
    'orderHistory.submitReceipt': 'Submit Receipt',
    'orderHistory.uploading': 'Uploading...',
    'orderHistory.paymentReceipt': 'Payment Receipt',
    'orderHistory.cancelConfirm': 'Are you sure you want to cancel this order?',
    'orderHistory.paymentSuccess': 'Payment successful!',
    'orderHistory.paymentPending': 'Payment submitted — order will be confirmed once your bank settles the transfer.',
    'orderHistory.paymentFailed': 'Payment failed:',
    'orderHistory.cancelFailed': 'Cancel failed:',
    'orderHistory.sessionExpired': 'Session expired, please login again',
    'orderHistory.loadFailed': 'Failed to load orders',
    'orderHistory.uploadFailed': 'Upload failed:',
    'orderHistory.evidenceFailed': 'Failed to load evidence:',

    // Order Delivery
    'delivery.title': 'Delivery Details',
    'delivery.orderStatus': 'Order Status',
    'delivery.deliveryInfo': 'Delivery Information',
    'delivery.orderDetails': 'Order Details',
    'delivery.customerName': 'Customer Name',
    'delivery.deliveryAddress': 'Delivery Address',
    'delivery.contactPhone': 'Contact Phone',
    'delivery.deliveryDate': 'Delivery Date',
    'delivery.actualDelivery': 'Actual Delivery',
    'delivery.deliveryNotes': 'Delivery Notes',
    'delivery.confirmReceipt': 'Confirm Receipt',
    'delivery.pleaseConfirm': 'Please confirm that you have received the delivery',
    'delivery.confirmButton': 'Confirm Receipt',
    'delivery.confirming': 'Confirming...',
    'delivery.deliveryComplete': 'Delivery Complete',
    'delivery.thankYou': 'Thank you for your order!',
    'delivery.viewMore': 'View More Orders',
    'delivery.deliveryEvidence': 'Delivery Evidence',
    'delivery.emptyGallons': 'Empty Gallons Returned',
    'delivery.borrowedGallons': 'Borrowed Gallons',
    'delivery.customerDiscount': 'Customer Discount',
    'delivery.orderTotal': 'Order Total',
    'delivery.refill': 'Refill',
    'delivery.tips': 'Please check the goods before confirming',
    'delivery.contact': 'If you have any questions, please contact customer service',
    'delivery.confirmMessage': 'Confirm receipt? This action cannot be undone.',
    'delivery.confirmSuccess': 'Receipt confirmed successfully!',
    'delivery.confirmFailed': 'Confirmation failed',
    'delivery.loadFailed': 'Loading Failed',
    'delivery.orderNotFound': 'Order not found',
    'delivery.returnToList': 'Return to Order List',
    'delivery.loadingOrder': 'Loading order information...',

    // Order Status
    'status.pending': 'Pending',
    'status.scheduled': 'Scheduled',
    'status.delivered': 'Delivered',
    'status.cancelled': 'Cancelled',
    'status.paid': 'Paid',
    'status.unpaid': 'Unpaid',
    'status.confirmed': 'Confirmed',
    'status.outForDelivery': 'Out for Delivery',

    // Progress Steps
    'progress.confirmed': 'Confirmed',
    'progress.delivering': 'Delivering',
    'progress.delivered': 'Delivered',
  },

  id: {
    // Navigation
    'nav.home': 'Beranda',
    'nav.myOrders': 'Pesanan Saya',
    'nav.newOrder': 'Pesan Baru',
    'nav.myAccount': 'Akun Saya',

    // Common
    'common.back': 'Kembali',
    'common.loading': 'Memuat...',
    'common.error': 'Kesalahan',
    'common.success': 'Berhasil',
    'common.confirm': 'Konfirmasi',
    'common.cancel': 'Batal',
    'common.save': 'Simpan',
    'common.close': 'Tutup',
    'common.total': 'Total',

    // Language
    'lang.switch': 'Bahasa',
    'lang.english': 'English',
    'lang.indonesian': 'Bahasa Indonesia',

    // Login
    'login.title': 'Pesan Air',
    'login.subtitle': 'Masukkan nomor WhatsApp Anda',
    'login.whatsappLabel': 'Nomor WhatsApp',
    'login.whatsappPlaceholder': '812-3456-7890',
    'login.continue': 'Lanjut',
    'login.checking': 'Memeriksa...',
    'login.notRegistered': 'Nomor belum terdaftar. Silakan daftar.',
    'login.register': 'Daftar Sekarang',
    'login.noAccount': 'Belum punya akun?',
    'login.registerHere': 'Daftar di sini',
    'login.tryOtherNumber': 'Coba nomor lain',

    // Register
    'register.title': 'Selamat Datang!',
    'register.subtitle': 'Daftar akun baru',
    'register.step1': 'Langkah 1: Isi formulir',
    'register.step2': 'Langkah 2: Verifikasi OTP WhatsApp',
    'register.formTitle': 'Formulir Pendaftaran',
    'register.otpTitle': 'Verifikasi WhatsApp',
    'register.otpSubtitle': 'Masukkan kode OTP yang dikirim ke WhatsApp Anda',
    'register.nameLabel': 'Nama Lengkap',
    'register.namePlaceholder': 'Budi Santoso',
    'register.addressLabel': 'Alamat Pengiriman',
    'register.addressPlaceholder': 'Jl. Sudirman No. 123, Jakarta Selatan',
    'register.whatsappLabel': 'Nomor WhatsApp',
    'register.buttonNext': 'Lanjut',
    'register.buttonSending': 'Mengirim OTP...',
    'register.buttonVerify': 'Selesaikan Pendaftaran',
    'register.buttonVerifying': 'Membuat Akun...',
    'register.otpExpires': 'Kode berlaku',
    'register.resendOtp': 'Kirim ulang kode OTP',
    'register.resendIn': 'Kirim ulang dalam',
    'register.changeNumber': 'Ubah Nomor',
    'register.haveAccount': 'Sudah punya akun?',
    'register.checkWhatsapp': 'Cek WhatsApp Anda untuk link pesanan',
    'register.nextStep': 'Langkah selanjutnya:',
    'register.openWhatsapp': 'Buka WhatsApp Anda dan klik link yang dikirim untuk mulai memesan!',
    'register.footerBonus': 'Dapat 2 voucher gratis saat pendaftaran',
    'register.errorRequired': 'Mohon isi semua field yang diperlukan',
    'register.successTitle': 'Pendaftaran Berhasil!',
    'register.successMessage': 'Link pesanan telah dikirim ke WhatsApp Anda. Silakan cek WhatsApp untuk melanjutkan.',
    'register.registrationComplete': 'Pendaftaran Selesai',
    'register.alreadyRegistered': 'Anda sudah terdaftar!',
    'register.loginLinkSent': 'Link masuk telah dikirim ke WhatsApp Anda.',
    'register.openChat': 'Buka chat dengan kami',
    'register.enterDashboard': 'Masuk ke Dashboard',
    'register.backToLogin': 'Kembali ke login',
    'register.numberRegistered': 'Nomor sudah terdaftar. Silakan login.',
    'register.didntReceive': 'Tidak menerima? Klik tombol di bawah.',
    'register.lostLink': 'Hilang link?',
    'register.getNewLink': 'Dapatkan link baru',
    'register.creatingAccount': 'Membuat akun Anda...',
    'register.newOtpSent': 'Kode OTP baru telah dikirim!',

    // Home
    'home.signOut': 'Keluar',
    'home.prepaid': 'Prabayar (Voucher)',
    'home.postpaid': 'Pascabayar (Invoice)',
    'home.voucherBalance': 'Saldo Voucher',
    'home.noVouchers': 'Belum ada voucher',
    'home.pendingOrders': 'Pesanan Pending',
    'home.delivery': 'Pengiriman:',
    'home.amount': 'Jumlah:',
    'home.scheduledMsg': 'Pesanan dijadwalkan — tidak dapat diedit',
    'home.orderDelivery': 'Pesan Pengiriman',
    'home.buyVouchers': 'Beli Voucher',
    'home.quickInfo': 'Info Cepat',
    'home.accountStatus': 'Status Akun',
    'home.active': 'Aktif',
    'home.pendingSetup': 'Menunggu Setup',
    'home.serviceBranch': 'Cabang Layanan',
    'home.billingCycle': 'Siklus Tagihan',
    'home.onDelivery': 'Sedang Dikirim',
    'home.unpaidAmount': 'Jumlah Belum Dibayar',
    'home.allPaid': 'Semua terbayar',
    'home.payNow': 'Bayar Sekarang',
    'home.lastDelivery': 'Pengiriman Terakhir',
    'home.shareApp': 'Bagikan Aplikasi',
    'home.scanShare': 'Pindai atau bagikan untuk membuka aplikasi',
    'home.share': 'Bagikan',
    'home.copyLink': 'Salin Tautan',
    'home.linkCopied': 'Tautan disalin!',
    'home.deleteConfirm': 'Anda yakin ingin menghapus pesanan ini?',
    'home.deleteSuccess': 'Pesanan dihapus!',
    'home.deleteFailed': 'Gagal menghapus: ',
    'home.noPendingOrders': 'Tidak ada pesanan pending',
    'home.loading': 'Memuat...',
    'home.edit': 'Edit',
    'home.delete': 'Hapus',

    // Branch Selection
    'branch.title': 'Pilih Cabang Air Anda',
    'branch.greeting': 'Cari alamat Anda untuk menemukan cabang terdekat.',
    'branch.searchPlaceholder': 'Cari alamat Anda...',
    'branch.searchHint': 'Ketuk dan pilih alamat Anda dari dropdown untuk menemukan cabang terdekat',
    'branch.yourLocation': 'Lokasi Anda',
    'branch.allBranches': 'Semua cabang (tidak ada di area layanan)',
    'branch.nearbyBranches': 'Cabang Terdekat',
    'branch.kmAway': 'km jauhnya',
    'branch.selected': 'Dipilih',
    'branch.selectAbove': 'Pilih cabang di atas',
    'branch.confirm': 'Konfirmasi',
    'branch.saving': 'Menyimpan...',
    'branch.sessionExpired': 'Sesi berakhir. Silakan login kembali.',
    'branch.saveFailed': 'Gagal menyimpan. Silakan coba lagi.',
    'branch.loading': 'Memuat...',

    // Vouchers / Top Up
    'vouchers.title': 'Isi Voucher',
    'vouchers.notAvailable': 'Voucher Tidak Tersedia',
    'vouchers.postpaidMsg': 'Akun Anda adalah mode pascabayar.\nVoucher hanya untuk pelanggan prabayar.',
    'vouchers.currentBalance': 'Saldo Saat Ini',
    'vouchers.refillPackages': 'Paket Isi Ulang',
    'vouchers.perVoucher': 'Per Voucher',
    'vouchers.perVoucherPrice': '/ voucher',
    'vouchers.otherProducts': 'Produk Lain',
    'vouchers.noProducts': 'Tidak ada produk tersedia.',
    'vouchers.buyNow': 'Beli Sekarang',
    'vouchers.loading': 'Memuat...',
    'vouchers.autoAdd': 'Saldo otomatis ditambahkan setelah pembayaran berhasil.',
    'vouchers.paymentSuccess': 'Pembayaran berhasil! Voucher ditambahkan.',
    'vouchers.paymentPending': 'Pembayaran dikirim — voucher akan ditambahkan setelah pembayaran selesai.',
    'vouchers.paymentFailed': 'Pembayaran gagal: ',
    'vouchers.paymentError': 'Error pembayaran: ',
    'vouchers.backToHome': '← Kembali ke Beranda',
    'vouchers.loadingPayment': 'Memuat...',

    // Account
    'account.title': 'Akun Saya',
    'account.profile': 'Profil',
    'account.settings': 'Pengaturan',
    'account.logout': 'Keluar',
    'account.prepaid': 'Prabayar',
    'account.postpaid': 'Pascabayar',
    'account.deliveryAddress': 'Alamat Pengiriman',
    'account.whatsapp': 'WhatsApp',
    'account.serviceBranch': 'Cabang Layanan',
    'account.pendingSetup': 'Menunggu Setup',
    'account.notAssigned': 'Belum ditetapkan',
    'account.voucherBalance': 'Saldo Voucher',
    'account.noVouchers': 'Belum ada voucher',
    'account.orderHistory': 'Riwayat Pesanan',
    'account.addressUpdated': 'Alamat diperbarui!',
    'account.updateFailed': 'Gagal memperbarui alamat: ',
    'account.saving': 'Menyimpan...',
    'account.save': 'Simpan',
    'account.cancel': 'Batal',
    'account.edit': 'Edit',

    // Place Order
    'placeOrder.title': 'Buat Pesanan Baru',
    'placeOrder.newDelivery': 'Pesan Baru',
    'placeOrder.editOrder': 'Edit Pesanan',
    'placeOrder.selectProducts': 'Pilih Produk',
    'placeOrder.deliveryDate': 'Tanggal Pengiriman',
    'placeOrder.notes': 'Catatan (Opsional)',
    'placeOrder.notesPlaceholder': 'Contoh: Taruh di depan pintu...',
    'placeOrder.orderSummary': 'Ringkasan Pesanan',
    'placeOrder.submit': 'Buat Pesanan',
    'placeOrder.update': 'Perbarui Pesanan',
    'placeOrder.submitting': 'Memproses...',
    'placeOrder.processing': 'Memproses...',
    'placeOrder.loadingProducts': 'Memuat produk...',
    'placeOrder.noProducts': 'Tidak ada produk tersedia.',
    'placeOrder.voucherBadge': 'voucher',
    'placeOrder.buy': 'Beli',
    'placeOrder.paymentBreakdown': 'Rincian Pembayaran',
    'placeOrder.voucherCovered': 'ditanggung voucher',
    'placeOrder.payViaQris': 'Bayar via QRIS',
    'placeOrder.outstandingBalance': 'Saldo Tertunggak',
    'placeOrder.outstandingDesc': 'Anda memiliki pesanan terkirim yang belum dibayar. Selesaikan pembayaran sebelum memesan baru.',
    'placeOrder.viewPayBills': 'Lihat & Bayar Tagihan',
    'placeOrder.backToHome': 'Kembali ke Beranda',
    'placeOrder.orderPlaced': 'Pesanan Dibuat!',
    'placeOrder.orderUpdated': 'Pesanan Diperbarui!',
    'placeOrder.orderPlacedDesc': 'Pesanan Anda telah diterima. Kami akan mengatur pengiriman segera.',
    'placeOrder.orderUpdatedDesc': 'Pesanan Anda berhasil diperbarui.',
    'placeOrder.unpaidBills': 'Tagihan Belum Dibayar',
    'placeOrder.unpaidBillsDesc': 'Anda memiliki tagihan belum dibayar. Selesaikan sebelum memesan baru.',
    'placeOrder.accessories': 'Aksesori',
    'placeOrder.showAccessories': 'Tampilkan Aksesori',
    'placeOrder.hideAccessories': 'Sembunyikan Aksesori',
    'placeOrder.disc': 'disk.',
    'placeOrder.failedSubmit': 'Gagal mengirim: ',
    'placeOrder.sessionExpired': 'Sesi berakhir, silakan login kembali',

    // Order History
    'orders.title': 'Riwayat Pesanan',
    'orders.empty': 'Belum Ada Pesanan',
    'orders.emptyDesc': 'Anda belum melakukan pesanan.\nMulai pesan untuk melihat riwayat di sini!',
    'orders.startOrdering': 'Mulai Pesan',
    'orders.errorLoading': 'Gagal Memuat Pesanan',
    'orders.tryAgain': 'Coba Lagi',
    'orders.orderId': 'Pesanan',
    'orders.deliveryDate': 'Tanggal Pengiriman',
    'orders.totalAmount': 'Total Pembayaran',
    'orders.paymentStatus': 'Status Pembayaran',
    'orders.orderedOn': 'Dipesan pada',
    'orders.viewDetails': 'Lihat Detail Pengiriman',
    'orderHistory.outstandingBalance': 'Saldo Tertunggak',
    'orderHistory.clear': 'Lunas',
    'orderHistory.borrowedGallons': 'Galon Dipinjam',
    'orderHistory.payViaQris': 'Bayar via QRIS',
    'orderHistory.bankTransfer': 'Transfer Bank',
    'orderHistory.loading': 'Memuat pesanan...',
    'orderHistory.newOrder': 'Pesanan Baru',
    'orderHistory.paid': 'Terbayar',
    'orderHistory.unpaid': 'Belum Dibayar',
    'orderHistory.orderConfirmedLocked': 'Terbayar — pesanan dikonfirmasi dan terkunci',
    'orderHistory.awaitingPayment': 'Menunggu pembayaran',
    'orderHistory.completePaymentQris': 'Selesaikan Pembayaran (QRIS)',
    'orderHistory.orderConfirmed': 'Pesanan dikonfirmasi — tidak dapat diedit atau dibatalkan',
    'orderHistory.viewPaymentReceipt': 'Lihat Kuitansi Pembayaran',
    'orderHistory.bank': 'Bank',
    'orderHistory.accountNumber': 'Nomor Rekening',
    'orderHistory.accountName': 'Nama Rekening',
    'orderHistory.transferAmount': 'Jumlah transfer:',
    'orderHistory.uploadReceipt': 'Unggah Kuitansi Pembayaran',
    'orderHistory.receiptUploaded': 'Kuitansi berhasil diunggah!',
    'orderHistory.confirmSoon': 'Kami akan mengkonfirmasi pembayaran Anda segera.',
    'orderHistory.selectPhoto': 'Pilih Foto',
    'orderHistory.submitReceipt': 'Kirim Kuitansi',
    'orderHistory.uploading': 'Mengunggah...',
    'orderHistory.paymentReceipt': 'Kuitansi Pembayaran',
    'orderHistory.cancelConfirm': 'Anda yakin ingin membatalkan pesanan ini?',
    'orderHistory.paymentSuccess': 'Pembayaran berhasil!',
    'orderHistory.paymentPending': 'Pembayaran dikirim — pesanan akan dikonfirmasi setelah bank menyelesaikan transfer.',
    'orderHistory.paymentFailed': 'Pembayaran gagal:',
    'orderHistory.cancelFailed': 'Pembatalan gagal:',
    'orderHistory.sessionExpired': 'Sesi berakhir, silakan login kembali',
    'orderHistory.loadFailed': 'Gagal memuat pesanan',
    'orderHistory.uploadFailed': 'Unggah gagal:',
    'orderHistory.evidenceFailed': 'Gagal memuat bukti:',

    // Order Delivery
    'delivery.title': 'Detail Pengiriman',
    'delivery.orderStatus': 'Status Pesanan',
    'delivery.deliveryInfo': 'Informasi Pengiriman',
    'delivery.orderDetails': 'Detail Pesanan',
    'delivery.customerName': 'Nama Pelanggan',
    'delivery.deliveryAddress': 'Alamat Pengiriman',
    'delivery.contactPhone': 'Nomor Telepon',
    'delivery.deliveryDate': 'Tanggal Pengiriman',
    'delivery.actualDelivery': 'Pengiriman Aktual',
    'delivery.deliveryNotes': 'Catatan Pengiriman',
    'delivery.confirmReceipt': 'Konfirmasi Penerimaan',
    'delivery.pleaseConfirm': 'Mohon konfirmasi bahwa Anda telah menerima pengiriman',
    'delivery.confirmButton': 'Konfirmasi Penerimaan',
    'delivery.confirming': 'Mengonfirmasi...',
    'delivery.deliveryComplete': 'Pengiriman Selesai',
    'delivery.thankYou': 'Terima kasih atas pesanan Anda!',
    'delivery.viewMore': 'Lihat Pesanan Lainnya',
    'delivery.deliveryEvidence': 'Bukti Pengiriman',
    'delivery.emptyGallons': 'Galon Kosong Dikembalikan',
    'delivery.borrowedGallons': 'Galon Dipinjam',
    'delivery.customerDiscount': 'Diskon Pelanggan',
    'delivery.orderTotal': 'Total Pesanan',
    'delivery.refill': 'Isi Ulang',
    'delivery.tips': 'Silakan periksa barang sebelum mengonfirmasi',
    'delivery.contact': 'Jika ada pertanyaan, hubungi layanan pelanggan',
    'delivery.confirmMessage': 'Konfirmasi penerimaan? Tindakan ini tidak dapat dibatalkan.',
    'delivery.confirmSuccess': 'Penerimaan berhasil dikonfirmasi!',
    'delivery.confirmFailed': 'Konfirmasi gagal',
    'delivery.loadFailed': 'Gagal Memuat',
    'delivery.orderNotFound': 'Pesanan tidak ditemukan',
    'delivery.returnToList': 'Kembali ke Daftar Pesanan',
    'delivery.loadingOrder': 'Memuat informasi pesanan...',

    // Order Status
    'status.pending': 'Menunggu',
    'status.scheduled': 'Dijadwalkan',
    'status.delivered': 'Terkirim',
    'status.cancelled': 'Dibatalkan',
    'status.paid': 'Dibayar',
    'status.unpaid': 'Belum Dibayar',
    'status.confirmed': 'Dikonfirmasi',
    'status.outForDelivery': 'Dalam Pengiriman',

    // Progress Steps
    'progress.confirmed': 'Dikonfirmasi',
    'progress.delivering': 'Dalam Pengiriman',
    'progress.delivered': 'Terkirim',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app_language');
    return (saved === 'en' || saved === 'id') ? saved : 'id';
  });

  useEffect(() => {
    localStorage.setItem('app_language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
